# This is meant to be used with the REST Client extension in VS Code

###
# Frank with password
GET https://localhost:7176/weatherforecast
username: frank
password: pete

###
# John who does not have a password but tries anyway
GET https://localhost:7176/weatherforecast
username: john
password: letmeingoddamnit